#!/bin/bash
# Test enrichment endpoint

echo "========================================================================"
echo "ENRICHMENT ENDPOINT TEST"
echo "========================================================================"
echo ""

# First, get your actual Render URL
echo "1. Get your Render backend URL from:"
echo "   https://dashboard.render.com"
echo "   (should be something like: apex-backend-xyz.onrender.com)"
echo ""

# Second, get a real contact UUID
echo "2. Get a contact UUID from your database:"
echo "   Option A: Check Dashboard and click a contact (UUID in URL)"
echo "   Option B: Query database:"
echo "   psql $DATABASE_URL -c \"SELECT id, name FROM contacts LIMIT 5;\""
echo ""

echo "3. Then run this command:"
echo ""
echo "   BACKEND_URL=\"https://YOUR-BACKEND.onrender.com\""
echo "   CONTACT_ID=\"your-contact-uuid-here\""
echo ""
echo "   curl -X POST \"\${BACKEND_URL}/api/v2/contacts/\${CONTACT_ID}/enrich\" \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -v"
echo ""
echo "========================================================================"
echo ""
echo "Example with fake values:"
echo ""
echo "curl -X POST \"https://apex-backend-abc123.onrender.com/api/v2/contacts/550e8400-e29b-41d4-a716-446655440000/enrich\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -v"
echo ""
echo "========================================================================"
echo ""
echo "Expected response (success):"
echo "{"
echo "  \"success\": true,"
echo "  \"contactId\": \"550e8400-e29b-41d4-a716-446655440000\","
echo "  \"status\": \"completed\","
echo "  \"sections\": 8,"
echo "  \"characterCount\": 2500"
echo "}"
echo ""
echo "Expected response (if contact not found):"
echo "{"
echo "  \"detail\": \"Contact not found\""
echo "}"
echo ""
